# This is a basic workflow to help you get started with Actions

name: Periodic start 

# Controls when the workflow will run
on:
 schedule:
   - cron: '30 18 * * *'
 workflow_dispatch:
   
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
     - name: Install Google Chrome
     - uses: browser-actions/setup-chrome@v1
       id: setup-chrome
     - run: |
          ${{ steps.setup-chrome.outputs.chrome-path }} --version
     - name: Install ChromeDriver
       run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          CHROME_DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.10'  # Укажите версию Python, которую вы используете
     - name: Install dependencies
       run: pip install -r selenium
     - name: Run Python Script
       run: python script.py 
