# This is a basic workflow to help you get started with Actions

name: Periodic start 

# Controls when the workflow will run
on:
 schedule:
   - cron: '30 18 * * *'
 workflow_dispatch:
   
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
     - name: Install Google Chrome
       uses: browser-actions/setup-chrome@v1
     - name: Running Chrome
       run: chrome --version
     - name: setup-chromedriver
       uses: nanasess/setup-chromedriver@v2.2.2
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.10'  # Укажите версию Python, которую вы используете
     - name: Install dependencies
       run: pip install selenium
     - name: Run Python Script
       run: python script.py 
